//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewSkills.LicenceServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LicenceServiceRef.ILicenceService")]
    public interface ILicenceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILicenceService/getLincenceRequest", ReplyAction="http://tempuri.org/ILicenceService/getLincenceRequestResponse")]
        int getLincenceRequest(string licenceNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILicenceServiceChannel : NewSkills.LicenceServiceRef.ILicenceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LicenceServiceClient : System.ServiceModel.ClientBase<NewSkills.LicenceServiceRef.ILicenceService>, NewSkills.LicenceServiceRef.ILicenceService {
        
        public LicenceServiceClient() {
        }
        
        public LicenceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LicenceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicenceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LicenceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int getLincenceRequest(string licenceNumber) {
            return base.Channel.getLincenceRequest(licenceNumber);
        }
    }
}
